server:
  port: 8888
spring:
  application:
    name: test-gateway-zuul
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 127.0.0.1:9200
      repositories:
        enabled: true





